### ISSUE TITLE
[Proposal]: Site Title instead of Logo

### ISSUE THREAD

**Issue by fakirlalon** [daviddarnes/alembic#172]
## Summary 
There should be an option to show Site Title instead of Site Logo. Some users might like to use only Site Title.

**Comment by daviddarnes** [comment]
Hey @fakirlalon! I've not had this request before, so I'm a little reluctant to add another option in. However you can customise your site to show the site title by creating the following file in your Jekyll project and updating the HTML with the site title instead of logo:
https://github.com/daviddarnes/alembic/blob/main/_includes/site-logo.html
