### ISSUE TITLE
[Question] Customizing Sidebar

### ISSUE THREAD

**Issue by adam-m-jcbs** [daviddarnes/alembic#91]
Thanks so much for this beautiful, flexible theme.  I'm pretty new to building sites with Jekyll, so forgive me if this is a naive question.

I've been trying to customize some of the theme's elements, in particular the sidebar.  I've been able to customize in some of the ways I want by copying `site-aside.html` into my local `_includes` directory.  However, I wanted to turn off the low opacity until hover mechanism.  I tried to do so my copying `_theme.scss` to my local `_sass`.  Changes to this local file do not seem to impact my site.  If I change it directly in the gemfile, I get the customization I want.  But I'd prefer not to modify the gemfile itself.  Do you have any guidance for doing this sort of customization?  What am I missing?

Thanks for your help!

**Comment by daviddarnes** [comment]
Hi @adam-m-jcbs, thanks so much for the kind words!!

You're going about this in the right way, but instead of copying the theme file try copying the main styles file (`/assets/styles.scss`). Makes sure to match the file path, front matter and import as shown here: https://github.com/daviddarnes/alembic/blob/master/assets/styles.scss

Then add underneath the following:
``` scss
.main .aside {
    opacity: 1;
}
```
That should overwrite the opacity styling in the cleanest fashion. Hope this works!

**Comment by adam-m-jcbs** [comment]
That worked great!  Thanks!
